### ISSUE TITLE
Ability to toggle/set placeholder by Profile

### ISSUE THREAD

**Issue by paulpv** [pedanticdan/obs-placeholder#1]
Thank you for this excellent solution that sure beats having to re-look-up where the placeholder file is stored.
I use OBS Virtual Camera on a work laptop.
95% of the time I use the virtual camera for work stuff.
Sometimes I use it for personal meetings, and it would be nice to not show my work's logo when in non-work usage.

I use OBS Profiles and Scenes to jump between personal and work settings.
It would be nice to be able to toggle between the placeholder image based on the active Profile.
There might be a hook for the plugin to know when the profile changes and to swap the image when that happens.

FYI: The placeholder.png path is pretty well known/fixed on Windows as `%PROGRAM_FILES_x86%\obs-studio\data\obs-plugins\win-dshow`, so maybe there might be a simple dumb way to implement the Windows side of this tool too?

**Comment by pedanticdan** [comment]
Sorry I didn't see this before. I'll looking it.

**Comment by pedanticdan** [comment]
It looks pretty straight forward for a plugin to get notified when the profiles changes.
I should also be able to add Windows support to the plugin with the following caveats:

1) Upgrading OBS will restore the default placeholder.png
2) clicking the plugin's "Reset to Default" button will have no effect.

**Comment by pedanticdan** [comment]
The requested enhancement has been implemented in MacOS Release v1.1.0.

A Windows version of the plugin is still under investigation.
