### ISSUE TITLE
Windows support (reply here)

### ISSUE THREAD

**Issue by FreshImmuc** [pedanticdan/obs-placeholder#4]
Please reply here, when the windows version is out! Thank you. Star then!

**Comment by pedanticdan** [comment]
This this issue different from https://github.com/pedanticdan/obs-placeholder/issues/3  ?

**Comment by FreshImmuc** [comment]
Yeah a bit but when will the Windows version be Released? The administrator thing wont be a problem for me!

**Comment by pedanticdan** [comment]
Prerelease now:

https://github.com/pedanticdan/obs-placeholder/releases/tag/v1.1.0rc1

**Comment by pedanticdan** [comment]
I think this can be closed now.
